// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbvb54KLRQy67adOG8HXzocR79GMnCMXk',
    appId: '1:908997914650:web:d10d6f479fc1abcb8d21a3',
    messagingSenderId: '908997914650',
    projectId: 'smart-pump-8ab25',
    authDomain: 'smart-pump-8ab25.firebaseapp.com',
    databaseURL: 'https://smart-pump-8ab25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pump-8ab25.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFpDh5eFlD1WdP1or2649Xh2VlYAYQ_Bg',
    appId: '1:908997914650:android:7c9a50e73bcd74118d21a3',
    messagingSenderId: '908997914650',
    projectId: 'smart-pump-8ab25',
    databaseURL: 'https://smart-pump-8ab25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pump-8ab25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZc0tsiFmIlwJBED3IqpCvfIDy3VnpwC8',
    appId: '1:908997914650:ios:97503047ce2f12448d21a3',
    messagingSenderId: '908997914650',
    projectId: 'smart-pump-8ab25',
    databaseURL: 'https://smart-pump-8ab25-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'smart-pump-8ab25.firebasestorage.app',
    iosBundleId: 'com.example.shimizuApp',
  );
}
